spring:
  application:
    name: haoke-banner
  profiles:
    active: mongodb,bannerNginx

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone:
        http://192.168.136.130:8761/eureka/
  instance:
    prefer-ip-address: true #优选IP作为服务的注册，发现，访问地址
